spring:
  mvc:
    throw-exception-if-no-handler-found: true
nacos:
  config:
    server-addr: console.yifeistudio.com:8848
    data-id: space-example-config
    group: space-example
  discovery:
    server-addr: console.yifeistudio.com:8848
